# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Booksstore NodeExpressMongo Web API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Booksstore NodeExpressMongo Web API ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./Projects/books-store-mean/webapi
    - run: npm run build --if-present
      working-directory: ./Projects/books-store-mean/webapi
    - run: npm test
      working-directory: ./Projects/books-store-mean/webapi
